spring:
  application:
    name: sf-kafka-integration

  kafka:
    bootstrap-servers: localhost:9092

camel:
  main:
    routes-include-pattern: classpath:camel/*,classpath:camel-template/*,classpath:camel-rest/*,routes/*.yaml
    context-reload-enabled: true

  component:
    kafka:
      brokers: ${spring.kafka.bootstrap-servers}
      auto-offset-reset: earliest
      group-id: sf-kafka-integration

logging:
  level:
    root: INFO
    com.sf.kafkaintegration: DEBUG
    org.apache.camel: INFO
